version: "3.3"
services:
  db:
    image: mysql:5.7
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  app:
    build: ./app
    links:
      - db
    ports:
      - "${BILLING_PORT}:5000"
    depends_on:
      - db
    restart: unless-stopped

networks:
    default:
        external:
            name: shared-net
