version: "3.3"
services:
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: unless-stopped
