version: "3.3"

services:
  db:
    image: mysql:8.0.25
    container_name: Db_container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_DATABASE: "weight"
    ports:
      - 3306
    volumes:
    - ./create-db.sql:/docker-entrypoint-initdb.d/create-db.sql

  web:
    build: .
    ports:
      - 5000:5000
    links: 
      - db
    command: ./entrypoint.sh 
