version: "3.3"

services:
    db:
      image: mysql:8.0.25
      container_name: Db_cont
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      volumes:
        - ./create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
      environment:
        MYSQL_ROOT_PASSWORD: "0000"
        MYSQL_DATABASE: "weight"
      ports:
      - 3306


    web:
      build: .
      ports:
        - ${WEIGHT_PORT}:5000
      links:
        - db
      command: ./entrypoint.sh
