version: "3.8"

services:
  database:
    container_name: mysql_cont
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    restart: always
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 1s
#        max_attempts: 3
#        window: default
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_DATABASE: "weight"
    ports:
      - 127.0.0.2:4000:3306
    volumes:
    - ./create-db.sql:/docker-entrypoint-initdb.d/create-db.sql



